name: Docker CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get Maven Project Version
        working-directory: myapp/
        run: |
          mvn clean --quiet
          current_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          new_version=$(echo $current_version | awk -F. '{print $1 "." $2 "." $3+1}')
          echo "New Version: $new_version" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        run: |
          docker buildx create --use
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker buildx build --platform linux/amd64,linux/arm64 -t $DOCKER_USERNAME/myapp:$new_version .

          # Push the inage with the new version
          docker push $DOCKER_USERNAME/myapp:$new_version

  run-pushed-image:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker
        uses: docker/setup-action@v2

      - name: Run Docker Image
        run: docker run -d -p 8080:8080 $DOCKER_USERNAME/myapp:$new_version
